---
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: tools
    values:
      layout: tool
permalink: pretty
collections:
  tools:
    output: true
